 ## Tensor

In [1]:
import torch
import numpy as np

## 指定Tensor大小，构建未初始化的Tensor

In [2]:
x = torch.Tensor(5, 3)
print(x)


 0.0000e+00  0.0000e+00  1.2107e-42
 0.0000e+00  7.0065e-45  1.8617e+25
 5.0710e+37  6.0116e-43  0.0000e+00
 0.0000e+00  7.0065e-45  1.8471e+25
 5.0738e+37  6.0116e-43  0.0000e+00
[torch.FloatTensor of size 5x3]



## 构建随机初始化的Tensor

In [3]:
y = torch.rand(5, 3)
print(y)
print(y.size)


 0.7139  0.4594  0.9405
 0.7795  0.0622  0.6561
 0.6556  0.2376  0.4662
 0.1250  0.9931  0.7257
 0.4262  0.9070  0.9179
[torch.FloatTensor of size 5x3]

<built-in method size of torch.FloatTensor object at 0x000001AD014A6348>


## torch.ones(size)构建指定size的全1矩阵

In [4]:
one = torch.ones(5, 3)
one


 1  1  1
 1  1  1
 1  1  1
 1  1  1
 1  1  1
[torch.FloatTensor of size 5x3]

## 下面表示的全是矩阵相加运算

- `y + one` # 运算符相加
- `torch.add(y,one)` # 相加
- `torch.add(y,one,result)` # 输出结果到result
- `y.add_(one)`  # 有`_`的操作表示替换当前值

In [5]:
y + one


 1.7139  1.4594  1.9405
 1.7795  1.0622  1.6561
 1.6556  1.2376  1.4662
 1.1250  1.9931  1.7257
 1.4262  1.9070  1.9179
[torch.FloatTensor of size 5x3]

In [6]:
torch.add(y,one)


 1.7139  1.4594  1.9405
 1.7795  1.0622  1.6561
 1.6556  1.2376  1.4662
 1.1250  1.9931  1.7257
 1.4262  1.9070  1.9179
[torch.FloatTensor of size 5x3]

In [7]:
result = torch.Tensor(5,3)
torch.add(y,one,out=result)
result


 1.7139  1.4594  1.9405
 1.7795  1.0622  1.6561
 1.6556  1.2376  1.4662
 1.1250  1.9931  1.7257
 1.4262  1.9070  1.9179
[torch.FloatTensor of size 5x3]

## 带有`_`的操作表示替换当前值

In [8]:
y.add_(one)  
y


 1.7139  1.4594  1.9405
 1.7795  1.0622  1.6561
 1.6556  1.2376  1.4662
 1.1250  1.9931  1.7257
 1.4262  1.9070  1.9179
[torch.FloatTensor of size 5x3]

## 张量也可以使用索引，切片等操作

In [9]:
result[0: 2, :]


 1.7139  1.4594  1.9405
 1.7795  1.0622  1.6561
[torch.FloatTensor of size 2x3]

## 如果要对Tensor做reshape/resize操作，使用`torch.view`



In [10]:
print(result.size())

view1 = result.view(15)
view2 = result.view(-1,5) # 传入参数`-1`表推断，同时只能有一个-1

print(view1.size())
print(view2.size())

torch.Size([5, 3])
torch.Size([15])
torch.Size([3, 5])


## **numpy和torch.tensor之间互转**

- **ndarray--> tensor**: ndarry变量`x`，使用`torch.from_numpy(x)`
- **tensor--> ndarray**: tensor变量`y`，使用`y.numpy()`

In [11]:
np1 = np.arange(6).reshape((2, 3)) # 创建一个ndarray
ten1 = torch.from_numpy(np1)  # ndarray->torch
np2 = ten1.numpy() # torch->ndarray

print("np:{}.format:{}".format(np1, type(np1)))
print("np-->torch:{}.format:{}".format(ten1, type(ten1)))
print("torch-->np:{}.format:{}".format(np2, type(np2)))

np:[[0 1 2]
 [3 4 5]].format:<class 'numpy.ndarray'>
np-->torch:
 0  1  2
 3  4  5
[torch.IntTensor of size 2x3]
.format:<class 'torch.IntTensor'>
torch-->np:[[0 1 2]
 [3 4 5]].format:<class 'numpy.ndarray'>


## ndarray和tensor共享存储空间

In [12]:
ten1.add_(1)
print(ten1)
print(np2)


 1  2  3
 4  5  6
[torch.IntTensor of size 2x3]

[[1 2 3]
 [4 5 6]]
